server:
  port: 8762
spring:
  security:
    user:
      name: root
      password: root
eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true     #是否使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #显示ip：port
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://root:root@eureka1:8761/eureka/
  server:
    enable-self-preservation: false     #关闭保护机制，以确保注册中心可以将不可用的实例剔除
