server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka2:8762/eureka/,http://root:root@eureka1:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #显示ip：port
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5    #心跳间隔
    lease-expiration-duration-in-seconds: 15
spring:
  application:
    name: product-server
management:
  endpoints:
    web:
      exposure:
        include: shutdown   #开启shutdown的端点访问
  endpoint:
    shutdown:
      enabled: true         #优雅停服开启
