server:
  port: 8006
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka2:8762/eureka/,http://root:root@eureka1:8761/eureka/
    register-with-eureka: true     #不注册到注册中心
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #显示ip：port
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5    #心跳间隔
    lease-expiration-duration-in-seconds: 15
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      #动态配置规则，通过文件加载
      datasource:
        ds1:
          file:
            file: classpath:flowRule.json
            data-type: json
            rule-type: flow
  application:
    name: order-server
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#feign对sentinel的支持
feign:
  sentinel:
    enabled: true
