package com.qiangqiang.entity;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.pid
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.type
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.title
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.percode
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String percode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.icon
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.href
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String href;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.target
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.open
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.ordernum
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.available
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer available;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.pid
     *
     * @return the value of sys_permission.pid
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.pid
     *
     * @param pid the value for sys_permission.pid
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.type
     *
     * @return the value of sys_permission.type
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.type
     *
     * @param type the value for sys_permission.type
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.title
     *
     * @return the value of sys_permission.title
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.title
     *
     * @param title the value for sys_permission.title
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.percode
     *
     * @return the value of sys_permission.percode
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getPercode() {
        return percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.percode
     *
     * @param percode the value for sys_permission.percode
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setPercode(String percode) {
        this.percode = percode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.icon
     *
     * @return the value of sys_permission.icon
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.icon
     *
     * @param icon the value for sys_permission.icon
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.href
     *
     * @return the value of sys_permission.href
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.href
     *
     * @param href the value for sys_permission.href
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.target
     *
     * @return the value of sys_permission.target
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.target
     *
     * @param target the value for sys_permission.target
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setTarget(String target) {
        this.target = target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.open
     *
     * @return the value of sys_permission.open
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.open
     *
     * @param open the value for sys_permission.open
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.ordernum
     *
     * @return the value of sys_permission.ordernum
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.ordernum
     *
     * @param ordernum the value for sys_permission.ordernum
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.available
     *
     * @return the value of sys_permission.available
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.available
     *
     * @param available the value for sys_permission.available
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }
}