server:
  port: 8001
  tomcat:
    max-threads: 10     #降低最大线程数方便模拟高并发
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka2:8762/eureka/,http://root:root@eureka1:8761/eureka/
    register-with-eureka: true     #不注册到注册中心
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #显示ip：port
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5    #心跳间隔
    lease-expiration-duration-in-seconds: 15
spring:
  application:
    name: order-server
  redis:
    # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为loaclhost）
    host: 127.0.0.1
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位毫秒）
    timeout: 10000ms
    # redis连接池配置
    lettuce:
      pool:
        # 最大可用连接数（默认为8，负数表示无限）
        max-active: 1024
        # 最大空闲连接数（默认为8，负数表示无限）
        max-idle: 200
        # 最小空闲连接数（默认为0，该值只有为正数才有用）
        min-idle: 5
        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
        max-wait: 10000ms
product-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  ConnecTimeout: 5000
  ReadTimeout: 5000


