spring:
  redis:
    timeout: 10000        # 连接超时时间
    host: 192.168.200.102  # Redis服务器地址
    port: 6379            # Redis服务器端口
    password:         # Redis服务器密码
    database: 0           # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 8  # 最大连接数，默认 8
        max-wait: -1   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 8     # 最大空闲连接，默认 8
        min-idle: 5       # 最小空闲连接，默认 0
server:
  port: 2222