package com.qiangqiang.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.loginname
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.address
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sex
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.remark
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.pwd
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.deptid
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer deptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.hiredate
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mgr
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer mgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.available
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ordernum
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.type
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.imgpath
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.salt
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    private String salt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.loginname
     *
     * @return the value of sys_user.loginname
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.loginname
     *
     * @param loginname the value for sys_user.loginname
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.address
     *
     * @return the value of sys_user.address
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.address
     *
     * @param address the value for sys_user.address
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sex
     *
     * @return the value of sys_user.sex
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sex
     *
     * @param sex the value for sys_user.sex
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.remark
     *
     * @return the value of sys_user.remark
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.remark
     *
     * @param remark the value for sys_user.remark
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.pwd
     *
     * @return the value of sys_user.pwd
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.pwd
     *
     * @param pwd the value for sys_user.pwd
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.deptid
     *
     * @return the value of sys_user.deptid
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.deptid
     *
     * @param deptid the value for sys_user.deptid
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.hiredate
     *
     * @return the value of sys_user.hiredate
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.hiredate
     *
     * @param hiredate the value for sys_user.hiredate
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mgr
     *
     * @return the value of sys_user.mgr
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getMgr() {
        return mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mgr
     *
     * @param mgr the value for sys_user.mgr
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setMgr(Integer mgr) {
        this.mgr = mgr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.available
     *
     * @return the value of sys_user.available
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.available
     *
     * @param available the value for sys_user.available
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ordernum
     *
     * @return the value of sys_user.ordernum
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ordernum
     *
     * @param ordernum the value for sys_user.ordernum
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.type
     *
     * @return the value of sys_user.type
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.type
     *
     * @param type the value for sys_user.type
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.imgpath
     *
     * @return the value of sys_user.imgpath
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.imgpath
     *
     * @param imgpath the value for sys_user.imgpath
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.salt
     *
     * @return the value of sys_user.salt
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.salt
     *
     * @param salt the value for sys_user.salt
     *
     * @mbggenerated Thu Dec 24 16:32:35 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }
}