spring:
  application:
    name: gateway-server-redis # 应用名称
  redis:
    timeout: 10000        # 连接超时时间
    host: 127.0.0.1  # Redis服务器地址
    port: 6379            # Redis服务器端口
    password:         # Redis服务器密码
    database: 1           # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024  # 最大连接数，默认 8
        max-wait: 10000   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200     # 最大空闲连接，默认 8
        min-idle: 5       # 最小空闲连接，默认 0
  cloud:
    gateway:
      # 路由规则
      routes:
      - id: product-server           # 路由 ID，唯一
        uri: lb://product-server     # lb:// 根据服务名称从注册中心获取服务请求地址
        predicates:                   # 断言（判断条件）
        # 匹配对应 URI 的请求，将匹配到的请求追加在目标 URI 之后
        - Path=/product/**
        filters:                       # 网关过滤器
        # 限流过滤器
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1 # 令牌桶每秒填充速率
            redis-rate-limiter.burstCapacity: 2 # 令牌桶总容量
            key-resolver: "#{@ipKeyResolver}" # 使用 SpEL 表达式按名称引用 bean
server:
  port: 10002
eureka:
  client:
    service-url:
      defaultZone: http://root:root@eureka2:8762/eureka/,http://root:root@eureka1:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #显示ip：port
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5    #心跳间隔
    lease-expiration-duration-in-seconds: 15